# Generated by Django 5.0.7 on 2024-08-01 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_article_img'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name': 'Article', 'verbose_name_plural': 'Articles'},
        ),
    ]
